config/routes.rb
Selfie::Application.routes.draw do

  resources :pins

  devise_for :users

  get 'about' => 'Pages#about'

  root :to => 'Pages#home'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description

  validates :description, presence: true, length: { maximum: 50 }

  belongs_to :user
  validates :user_id, presence: true 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable #, :recoverable ~for forgot pass function

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
  
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_filter :set_pin, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @pins = Pin.all
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.new 
    respond_with(@pin)
  end

  def edit
    @pin = current_user.pins.find(params[:id])
  end

  def create
    @pin = current_user.pins.new(params[:pin])
    @pin.save
    respond_with(@pin)
  end

  def update
    @current_user.pins.update_attributes(params[:pin])
    respond_with(@pin)
  end

  def destroy
    @current_user.pins.destroy
    respond_with(@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "Contact Us","#" %>
	</small>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Selfie Challenge", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
         
        <% if user_signed_in? %>
        <li><%= link_to "Edit Profile",edit_user_registration_path %></li>
        <li><%= link_to "Logout",destroy_user_session_path, method: :delete %></li>

        <% else %>
        
        <li><%= link_to "Sign Up",new_user_registration_path%></li>
        <li><%= link_to "Login",new_user_session_path %></li>
        
        <% end %>

        <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search Selfies">
        </div>
        <button type="submit" class="btn btn-default">Find!</button>
      </form>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Selfie Challenge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	<%end%>
<%= yield %>

<%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>

<p>
   d2ewfwefwefefwefwefewfew
</p>

app/views/pages/home.html.erb
<div class="jumbotron">
			<h1>Selfie Challenge</h1>
				<p>

					The best selfie wins!
					
				</p>
				<p>

					<%=  link_to "Sign Up & Post Your First Selfie", new_user_registration_path, class: "btn btn-success btn-lg"  %>

				</p>
		</div>
	

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, :html => { :role => 'form'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description, as: :text, input_html: {rows: "3"} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<tr>
    <td><%= pin.description %></td>
    <td><%= link_to 'Show', pin %></td>
    <% if current_user == pin.user %>
	    <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
	    <td><%= link_to 'Self Destruct', pin, method: :delete, data: { confirm: 'Are you sure my nigga?' } %></td>
	<% end %>
 </tr>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

  <tbody>
  <%= render @pins %>
  </tbody>
</table>

<br />

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="well">
			<p>
			    <%= @pin.description %>
			</p>
			<p>
			    <%= @pin.user.name %>
			</p>
			<% if current_user == @pin.user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<% end %>
			<%= link_to 'Back', pins_path %>

		</div>
	</div>
</div>